table 'Date Dimensions'
	lineageTag: 24844603-444d-485d-8127-28c784e11545

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: fee25a36-4ed1-4078-b4ae-692bc7ebf007
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 4fb46b4e-ef3a-429d-9b4a-ab1054f76aeb
			defaultHierarchy: LocalDateTable_6b15dac2-d4c7-436b-acaa-46f4935ed283.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 688fb715-b979-4399-aab8-9d0bce372773
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: 98e66e3e-8738-4a32-9b9f-81031fd3fbaf
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	partition 'Date Dimensions' = m
		mode: import
		source = ```
				let
				    Source = List.Dates(
				    #date(2016, 1, 1),
				    43830 - 42370 + 1, 
				    #duration(1, 0, 0, 0)
				),
				    #"Converted to Table" = List.Dates(
				    #date(2016, 1, 1), // It's still safer to use the clear format for the start date
				    43830 - 42370 + 1, // Number of days: (43830 is Dec 31, 2019) - (42370 is Jan 1, 2016) + 1
				    #duration(1, 0, 0, 0)
				),
				    #"Converted to Table1" = Table.FromList(#"Converted to Table", Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Converted to Table1",{{"Column1", type date}}),
				    #"Inserted Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Column1]), Int64.Type),
				    #"Inserted Month" = Table.AddColumn(#"Inserted Year", "Month", each Date.Month([Column1]), Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Inserted Month",{{"Column1", "Date"}})
				in
				    #"Renamed Columns"
				```

	changedProperty = Name

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

