table 'Dedicated Measures'
	lineageTag: 636bdef9-737d-4356-9bcc-60e94853eddf

	measure 'Total Consumption' =
			Sum (
			    'Energy Consumptions'[Consumption Values]
			    )
		formatString: 0
		lineageTag: 9c0bd8e3-9b0d-403f-b528-6dcc1b09e44e

	measure 'Total Electricity Units' =
			CALCULATE(
			    [Total Consumption], 'Rates'[Energy Type] = "Electricity"
			    )
		lineageTag: 21aed90a-cc82-4504-aa3f-f1cfa8daef7c

	measure 'Total Gas Units' =
			CALCULATE(
			    [Total Consumption], 'Rates'[Energy Type] = "Gas"
			    )
		lineageTag: cc14e337-67bb-4472-9a05-2759405af170

	measure 'Total Water Units' =
			CALCULATE(
			    [Total Consumption], 'Rates'[Energy Type] = "Water"
			    )
		lineageTag: e9797353-de36-477d-b119-384a3d203532

	partition 'Dedicated Measures' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [C = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"C", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"C"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

