table Rates
	lineageTag: 0e1fc25a-b12a-4685-8d22-959c59005191

	column Year
		dataType: int64
		formatString: 0
		lineageTag: ed985a10-0d3e-4a22-afea-a0cb747c3a80
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Energy Type'
		dataType: string
		lineageTag: a6fcb13b-40fe-4878-b069-caddcf99b503
		summarizeBy: none
		sourceColumn: Energy Type

		annotation SummarizationSetBy = Automatic

	column 'Price Per Unit'
		dataType: double
		lineageTag: f2291ad4-cc38-4284-b22d-5784d94ca9ea
		summarizeBy: none
		sourceColumn: Price Per Unit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Rate Key'
		dataType: string
		lineageTag: 33811738-1d97-461a-98c5-90fb9c7d5b8b
		summarizeBy: none
		sourceColumn: Rate Key

		annotation SummarizationSetBy = Automatic

	partition Rates = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\wyatt\OneDrive\Desktop\Personal Docs\School\CS-226 SQL\Energy Consumption\Energy Consumptions Dataset.xlsx"), null, true),
				    Rates_Sheet = Source{[Item="Rates",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Rates_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Year", Int64.Type}, {"Energy Type", type text}, {"Price Per Unit", type number}}),
				    #"Inserted Merged Column" = Table.AddColumn(#"Changed Type", "Rate_Key", each Text.Combine({Text.From([Year], "en-US"), [Energy Type]}, "_"), type text),
				    #"Renamed Columns" = Table.RenameColumns(#"Inserted Merged Column",{{"Rate_Key", "Rate Key"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

